/* This file is generated by scripts/generate-component-registry.mjs. Do not edit manually. */

import type { Component } from 'vue'

import PuAccordion from './components/puAccordion/puAccordion.vue'
import PuAccordionItem from './components/puAccordion/puAccordionItem.vue'
import PuAnnouncementBar from './components/puAnnouncementBar/puAnnouncementBar.vue'
import PuBentoGrid from './components/puBentoGrid/puBentoGrid.vue'
import PuBentoItem from './components/puBentoItem/puBentoItem.vue'
import PuButton from './components/puButton/puButton.vue'
import PuCard from './components/puCard/puCard.vue'
import PuCell from './components/puCell/puCell.vue'
import PuCellGroup from './components/puCellGroup/puCellGroup.vue'
import PuCheckbox from './components/puCheckbox/puCheckbox.vue'
import PuCheckboxGroup from './components/puCheckboxGroup/puCheckboxGroup.vue'
import PuChip from './components/puChip/puChip.vue'
import PuChipGroup from './components/puChipGroup/puChipGroup.vue'
import PuChipInput from './components/puChipInput/puChipInput.vue'
import PuChipsEditor from './components/puChipsEditor/puChipsEditor.vue'
import PuDescriptionItem from './components/puDescriptionItem/puDescriptionItem.vue'
import PuDescriptionList from './components/puDescriptionList/puDescriptionList.vue'
import PuDialog from './components/puDialog/puDialog.vue'
import PuDrawer from './components/puDrawer/puDrawer.vue'
import PuEmptyState from './components/puEmptyState/puEmptyState.vue'
import PuFilesUpload from './components/puFilesUpload/puFilesUpload.vue'
import PuFileUpload from './components/puFileUpload/puFileUpload.vue'
import PuForm from './components/puForm/puForm.vue'
import PuFormItem from './components/puFormItem/puFormItem.vue'
import PuImg from './components/puImg/puImg.vue'
import PuImgCropper from './components/puImgCropper/puImgCropper.vue'
import PuInlineNotice from './components/puInlineNotice/puInlineNotice.vue'
import PuInput from './components/puInput/puInput.vue'
import PuLoadingState from './components/puLoadingState/puLoadingState.vue'
import PuModal from './components/puModal/puModal.vue'
import PuMultiStopToggle from './components/puMultiStopToggle/puMultiStopToggle.vue'
import PuNumberInput from './components/puNumberInput/puNumberInput.vue'
import PuPageHeader from './components/puPageHeader/puPageHeader.vue'
import PuPageScaffold from './components/puPageScaffold/puPageScaffold.vue'
import PuPicker from './components/puPicker/puPicker.vue'
import PuScrollView from './components/puScrollView/puScrollView.vue'
import PuSegmented from './components/puSegmented/puSegmented.vue'
import PuSegmentedItem from './components/puSegmentedItem/puSegmentedItem.vue'
import PuSelect from './components/puSelect/puSelect.vue'
import PuSkeleton from './components/puSkeleton/puSkeleton.vue'
import PuSnackbar from './components/puSnackbar/puSnackbar.vue'
import PuSnackbarHost from './components/puSnackbar/puSnackbarHost.vue'
import PuSpinner from './components/puSpinner/puSpinner.vue'
import PuTab from './components/puTab/puTab.vue'
import PuTabs from './components/puTabs/puTabs.vue'
import PuTag from './components/puTag/puTag.vue'
import PuTextarea from './components/puTextarea/puTextarea.vue'
import PuToggleSwitch from './components/puToggleSwitch/puToggleSwitch.vue'
import PuWheelPicker from './components/puWheelPicker/puWheelPicker.vue'

export {
  PuAccordion,
  PuAccordionItem,
  PuAnnouncementBar,
  PuBentoGrid,
  PuBentoItem,
  PuButton,
  PuCard,
  PuCell,
  PuCellGroup,
  PuCheckbox,
  PuCheckboxGroup,
  PuChip,
  PuChipGroup,
  PuChipInput,
  PuChipsEditor,
  PuDescriptionItem,
  PuDescriptionList,
  PuDialog,
  PuDrawer,
  PuEmptyState,
  PuFilesUpload,
  PuFileUpload,
  PuForm,
  PuFormItem,
  PuImg,
  PuImgCropper,
  PuInlineNotice,
  PuInput,
  PuLoadingState,
  PuModal,
  PuMultiStopToggle,
  PuNumberInput,
  PuPageHeader,
  PuPageScaffold,
  PuPicker,
  PuScrollView,
  PuSegmented,
  PuSegmentedItem,
  PuSelect,
  PuSkeleton,
  PuSnackbar,
  PuSnackbarHost,
  PuSpinner,
  PuTab,
  PuTabs,
  PuTag,
  PuTextarea,
  PuToggleSwitch,
  PuWheelPicker
}

export type * from './components/puAccordion/puAccordion'
export type * from './components/puAccordion/puAccordionItem'
export type * from './components/puAnnouncementBar/puAnnouncementBar'
export type * from './components/puBentoGrid/puBentoGrid'
export type * from './components/puBentoItem/puBentoItem'
export type * from './components/puButton/puButton'
export type * from './components/puCard/puCard'
export type * from './components/puCell/puCell'
export type * from './components/puCellGroup/puCellGroup'
export type * from './components/puCheckbox/puCheckbox'
export type * from './components/puCheckboxGroup/puCheckboxGroup'
export type * from './components/puChip/puChip'
export type * from './components/puChipGroup/puChipGroup'
export type * from './components/puChipInput/puChipInput'
export type * from './components/puChipsEditor/puChipsEditor'
export type * from './components/puDescriptionItem/puDescriptionItem'
export type * from './components/puDescriptionList/puDescriptionList'
export type * from './components/puDialog/puDialog'
export type * from './components/puDrawer/puDrawer'
export type * from './components/puEmptyState/puEmptyState'
export type * from './components/puFilesUpload/puFilesUpload'
export type * from './components/puFileUpload/puFileUpload'
export type * from './components/puForm/puForm'
export type * from './components/puFormItem/puFormItem'
export type * from './components/puImg/puImg'
export type * from './components/puImgCropper/puImgCropper'
export type * from './components/puInlineNotice/puInlineNotice'
export type * from './components/puInput/puInput'
export type * from './components/puLoadingState/puLoadingState'
export type * from './components/puModal/puModal'
export type * from './components/puMultiStopToggle/puMultiStopToggle'
export type * from './components/puNumberInput/puNumberInput'
export type * from './components/puPageHeader/puPageHeader'
export type * from './components/puPageScaffold/puPageScaffold'
export type * from './components/puPicker/puPicker'
export type * from './components/puScrollView/puScrollView'
export type * from './components/puSegmented/puSegmented'
export type * from './components/puSegmentedItem/puSegmentedItem'
export type * from './components/puSelect/puSelect'
export type * from './components/puSkeleton/puSkeleton'
export type * from './components/puSnackbar/puSnackbar'
export type * from './components/puSnackbar/puSnackbarHost'
export type * from './components/puSpinner/puSpinner'
export type * from './components/puTab/puTab'
export type * from './components/puTabs/puTabs'
export type * from './components/puTag/puTag'
export type * from './components/puTextarea/puTextarea'
export type * from './components/puToggleSwitch/puToggleSwitch'
export type * from './components/puWheelPicker/puWheelPicker'

declare module 'vue' {
  export interface GlobalComponents {
    PuAccordion: typeof PuAccordion
    PuAccordionItem: typeof PuAccordionItem
    PuAnnouncementBar: typeof PuAnnouncementBar
    PuBentoGrid: typeof PuBentoGrid
    PuBentoItem: typeof PuBentoItem
    PuButton: typeof PuButton
    PuCard: typeof PuCard
    PuCell: typeof PuCell
    PuCellGroup: typeof PuCellGroup
    PuCheckbox: typeof PuCheckbox
    PuCheckboxGroup: typeof PuCheckboxGroup
    PuChip: typeof PuChip
    PuChipGroup: typeof PuChipGroup
    PuChipInput: typeof PuChipInput
    PuChipsEditor: typeof PuChipsEditor
    PuDescriptionItem: typeof PuDescriptionItem
    PuDescriptionList: typeof PuDescriptionList
    PuDialog: typeof PuDialog
    PuDrawer: typeof PuDrawer
    PuEmptyState: typeof PuEmptyState
    PuFilesUpload: typeof PuFilesUpload
    PuFileUpload: typeof PuFileUpload
    PuForm: typeof PuForm
    PuFormItem: typeof PuFormItem
    PuImg: typeof PuImg
    PuImgCropper: typeof PuImgCropper
    PuInlineNotice: typeof PuInlineNotice
    PuInput: typeof PuInput
    PuLoadingState: typeof PuLoadingState
    PuModal: typeof PuModal
    PuMultiStopToggle: typeof PuMultiStopToggle
    PuNumberInput: typeof PuNumberInput
    PuPageHeader: typeof PuPageHeader
    PuPageScaffold: typeof PuPageScaffold
    PuPicker: typeof PuPicker
    PuScrollView: typeof PuScrollView
    PuSegmented: typeof PuSegmented
    PuSegmentedItem: typeof PuSegmentedItem
    PuSelect: typeof PuSelect
    PuSkeleton: typeof PuSkeleton
    PuSnackbar: typeof PuSnackbar
    PuSnackbarHost: typeof PuSnackbarHost
    PuSpinner: typeof PuSpinner
    PuTab: typeof PuTab
    PuTabs: typeof PuTabs
    PuTag: typeof PuTag
    PuTextarea: typeof PuTextarea
    PuToggleSwitch: typeof PuToggleSwitch
    PuWheelPicker: typeof PuWheelPicker
  }
}

type ComponentEntry = readonly [name: string, component: Component]

const components: readonly ComponentEntry[] = [
  ['PuAccordion', PuAccordion],
  ['PuAccordionItem', PuAccordionItem],
  ['PuAnnouncementBar', PuAnnouncementBar],
  ['PuBentoGrid', PuBentoGrid],
  ['PuBentoItem', PuBentoItem],
  ['PuButton', PuButton],
  ['PuCard', PuCard],
  ['PuCell', PuCell],
  ['PuCellGroup', PuCellGroup],
  ['PuCheckbox', PuCheckbox],
  ['PuCheckboxGroup', PuCheckboxGroup],
  ['PuChip', PuChip],
  ['PuChipGroup', PuChipGroup],
  ['PuChipInput', PuChipInput],
  ['PuChipsEditor', PuChipsEditor],
  ['PuDescriptionItem', PuDescriptionItem],
  ['PuDescriptionList', PuDescriptionList],
  ['PuDialog', PuDialog],
  ['PuDrawer', PuDrawer],
  ['PuEmptyState', PuEmptyState],
  ['PuFilesUpload', PuFilesUpload],
  ['PuFileUpload', PuFileUpload],
  ['PuForm', PuForm],
  ['PuFormItem', PuFormItem],
  ['PuImg', PuImg],
  ['PuImgCropper', PuImgCropper],
  ['PuInlineNotice', PuInlineNotice],
  ['PuInput', PuInput],
  ['PuLoadingState', PuLoadingState],
  ['PuModal', PuModal],
  ['PuMultiStopToggle', PuMultiStopToggle],
  ['PuNumberInput', PuNumberInput],
  ['PuPageHeader', PuPageHeader],
  ['PuPageScaffold', PuPageScaffold],
  ['PuPicker', PuPicker],
  ['PuScrollView', PuScrollView],
  ['PuSegmented', PuSegmented],
  ['PuSegmentedItem', PuSegmentedItem],
  ['PuSelect', PuSelect],
  ['PuSkeleton', PuSkeleton],
  ['PuSnackbar', PuSnackbar],
  ['PuSnackbarHost', PuSnackbarHost],
  ['PuSpinner', PuSpinner],
  ['PuTab', PuTab],
  ['PuTabs', PuTabs],
  ['PuTag', PuTag],
  ['PuTextarea', PuTextarea],
  ['PuToggleSwitch', PuToggleSwitch],
  ['PuWheelPicker', PuWheelPicker]
]

export default components
