/* This file is generated by scripts/generate-component-registry.mjs. Do not edit manually. */

import type { Component } from 'vue'

import PuAccordion from './components/puAccordion/puAccordion.vue'
import PuAccordionItem from './components/puAccordion/puAccordionItem.vue'
import PuAnnouncementBar from './components/puAnnouncementBar/puAnnouncementBar.vue'
import PuBentoGrid from './components/puBentoGrid/puBentoGrid.vue'
import PuBentoItem from './components/puBentoItem/puBentoItem.vue'
import PuButton from './components/puButton/puButton.vue'
import PuCard from './components/puCard/puCard.vue'
import PuCell from './components/puCell/puCell.vue'
import PuCellGroup from './components/puCellGroup/puCellGroup.vue'
import PuCheckbox from './components/puCheckbox/puCheckbox.vue'
import PuCheckboxGroup from './components/puCheckboxGroup/puCheckboxGroup.vue'
import PuChip from './components/puChip/puChip.vue'
import PuChipGroup from './components/puChipGroup/puChipGroup.vue'
import PuDescriptionItem from './components/puDescriptionItem/puDescriptionItem.vue'
import PuDescriptionList from './components/puDescriptionList/puDescriptionList.vue'
import PuDialog from './components/puDialog/puDialog.vue'
import PuDrawer from './components/puDrawer/puDrawer.vue'
import PuEmptyState from './components/puEmptyState/puEmptyState.vue'
import PuFilesUpload from './components/puFilesUpload/puFilesUpload.vue'
import PuFileUpload from './components/puFileUpload/puFileUpload.vue'
import PuForm from './components/puForm/puForm.vue'
import PuFormItem from './components/puFormItem/puFormItem.vue'
import PuImg from './components/puImg/puImg.vue'
import PuImgCropper from './components/puImgCropper/puImgCropper.vue'
import PuInlineNotice from './components/puInlineNotice/puInlineNotice.vue'
import PuInput from './components/puInput/puInput.vue'
import PuModal from './components/puModal/puModal.vue'
import PuPageHeader from './components/puPageHeader/puPageHeader.vue'
import PuPageScaffold from './components/puPageScaffold/puPageScaffold.vue'
import PuPicker from './components/puPicker/puPicker.vue'
import PuScrollView from './components/puScrollView/puScrollView.vue'
import PuSegmented from './components/puSegmented/puSegmented.vue'
import PuSegmentedItem from './components/puSegmentedItem/puSegmentedItem.vue'
import PuSkeleton from './components/puSkeleton/puSkeleton.vue'
import PuSnackbar from './components/puSnackbar/puSnackbar.vue'
import PuSnackbarHost from './components/puSnackbar/puSnackbarHost.vue'
import PuSpinner from './components/puSpinner/puSpinner.vue'
import PuTab from './components/puTab/puTab.vue'
import PuTabs from './components/puTabs/puTabs.vue'
import PuTag from './components/puTag/puTag.vue'
import PuTextarea from './components/puTextarea/puTextarea.vue'
import PuToggleSwitch from './components/puToggleSwitch/puToggleSwitch.vue'
import PuWheelPicker from './components/puWheelPicker/puWheelPicker.vue'

export {
  PuAccordion,
  PuAccordionItem,
  PuAnnouncementBar,
  PuBentoGrid,
  PuBentoItem,
  PuButton,
  PuCard,
  PuCell,
  PuCellGroup,
  PuCheckbox,
  PuCheckboxGroup,
  PuChip,
  PuChipGroup,
  PuDescriptionItem,
  PuDescriptionList,
  PuDialog,
  PuDrawer,
  PuEmptyState,
  PuFilesUpload,
  PuFileUpload,
  PuForm,
  PuFormItem,
  PuImg,
  PuImgCropper,
  PuInlineNotice,
  PuInput,
  PuModal,
  PuPageHeader,
  PuPageScaffold,
  PuPicker,
  PuScrollView,
  PuSegmented,
  PuSegmentedItem,
  PuSkeleton,
  PuSnackbar,
  PuSnackbarHost,
  PuSpinner,
  PuTab,
  PuTabs,
  PuTag,
  PuTextarea,
  PuToggleSwitch,
  PuWheelPicker
}

type ComponentEntry = readonly [name: string, component: Component]

const components: readonly ComponentEntry[] = [
  ['PuAccordion', PuAccordion],
  ['PuAccordionItem', PuAccordionItem],
  ['PuAnnouncementBar', PuAnnouncementBar],
  ['PuBentoGrid', PuBentoGrid],
  ['PuBentoItem', PuBentoItem],
  ['PuButton', PuButton],
  ['PuCard', PuCard],
  ['PuCell', PuCell],
  ['PuCellGroup', PuCellGroup],
  ['PuCheckbox', PuCheckbox],
  ['PuCheckboxGroup', PuCheckboxGroup],
  ['PuChip', PuChip],
  ['PuChipGroup', PuChipGroup],
  ['PuDescriptionItem', PuDescriptionItem],
  ['PuDescriptionList', PuDescriptionList],
  ['PuDialog', PuDialog],
  ['PuDrawer', PuDrawer],
  ['PuEmptyState', PuEmptyState],
  ['PuFilesUpload', PuFilesUpload],
  ['PuFileUpload', PuFileUpload],
  ['PuForm', PuForm],
  ['PuFormItem', PuFormItem],
  ['PuImg', PuImg],
  ['PuImgCropper', PuImgCropper],
  ['PuInlineNotice', PuInlineNotice],
  ['PuInput', PuInput],
  ['PuModal', PuModal],
  ['PuPageHeader', PuPageHeader],
  ['PuPageScaffold', PuPageScaffold],
  ['PuPicker', PuPicker],
  ['PuScrollView', PuScrollView],
  ['PuSegmented', PuSegmented],
  ['PuSegmentedItem', PuSegmentedItem],
  ['PuSkeleton', PuSkeleton],
  ['PuSnackbar', PuSnackbar],
  ['PuSnackbarHost', PuSnackbarHost],
  ['PuSpinner', PuSpinner],
  ['PuTab', PuTab],
  ['PuTabs', PuTabs],
  ['PuTag', PuTag],
  ['PuTextarea', PuTextarea],
  ['PuToggleSwitch', PuToggleSwitch],
  ['PuWheelPicker', PuWheelPicker]
]

export default components
