/* This file is generated by scripts/generate-component-registry.mjs. Do not edit manually. */

import type { Component } from 'vue'

import PuAccordion from './components/puAccordion/puAccordion.vue'
import PuAccordionItem from './components/puAccordion/puAccordionItem.vue'
import PuButton from './components/puButton/puButton.vue'
import PuCell from './components/puCell/puCell.vue'
import PuCheckbox from './components/puCheckbox/puCheckbox.vue'
import PuCheckboxGroup from './components/puCheckboxGroup/puCheckboxGroup.vue'
import PuChip from './components/puChip/puChip.vue'
import PuChipGroup from './components/puChipGroup/puChipGroup.vue'
import PuDescriptionItem from './components/puDescriptionItem/puDescriptionItem.vue'
import PuDescriptionList from './components/puDescriptionList/puDescriptionList.vue'
import PuDesktopPageScaffold from './components/puDesktopPageScaffold/puDesktopPageScaffold.vue'
import PuDrawer from './components/puDrawer/puDrawer.vue'
import PuExpandableCard from './components/puExpandableCard/puExpandableCard.vue'
import PuFooterRevealPageScaffold from './components/puFooterRevealPageScaffold/puFooterRevealPageScaffold.vue'
import PuForm from './components/puForm/puForm.vue'
import PuFormItem from './components/puFormItem/puFormItem.vue'
import PuFullScreenPageScaffold from './components/puFullScreenPageScaffold/puFullScreenPageScaffold.vue'
import PuImg from './components/puImg/puImg.vue'
import PuImgCropper from './components/puImgCropper/puImgCropper.vue'
import PuInfoRow from './components/puInfoRow/puInfoRow.vue'
import PuInput from './components/puInput/puInput.vue'
import PuModal from './components/puModal/puModal.vue'
import PuNoticeBar from './components/puNoticeBar/puNoticeBar.vue'
import PuPageHeader from './components/puPageHeader/puPageHeader.vue'
import PuPageScaffold from './components/puPageScaffold/puPageScaffold.vue'
import PuPageScaffoldCentered from './components/puPageScaffoldCentered/puPageScaffoldCentered.vue'
import PuPageScaffoldFlow from './components/puPageScaffoldFlow/puPageScaffoldFlow.vue'
import PuPicker from './components/puPicker/puPicker.vue'
import PuScrollView from './components/puScrollView/puScrollView.vue'
import PuSurfaceCard from './components/puSurfaceCard/puSurfaceCard.vue'
import PuTab from './components/puTab/puTab.vue'
import PuTabs from './components/puTabs/puTabs.vue'
import PuTag from './components/puTag/puTag.vue'
import PuTextarea from './components/puTextarea/puTextarea.vue'
import PuToggleSwitch from './components/puToggleSwitch/puToggleSwitch.vue'
import PuWheelPicker from './components/puWheelPicker/puWheelPicker.vue'

export {
  PuAccordion,
  PuAccordionItem,
  PuButton,
  PuCell,
  PuCheckbox,
  PuCheckboxGroup,
  PuChip,
  PuChipGroup,
  PuDescriptionItem,
  PuDescriptionList,
  PuDesktopPageScaffold,
  PuDrawer,
  PuExpandableCard,
  PuFooterRevealPageScaffold,
  PuForm,
  PuFormItem,
  PuFullScreenPageScaffold,
  PuImg,
  PuImgCropper,
  PuInfoRow,
  PuInput,
  PuModal,
  PuNoticeBar,
  PuPageHeader,
  PuPageScaffold,
  PuPageScaffoldCentered,
  PuPageScaffoldFlow,
  PuPicker,
  PuScrollView,
  PuSurfaceCard,
  PuTab,
  PuTabs,
  PuTag,
  PuTextarea,
  PuToggleSwitch,
  PuWheelPicker
}

type ComponentEntry = readonly [name: string, component: Component]

const components: readonly ComponentEntry[] = [
  ['PuAccordion', PuAccordion],
  ['PuAccordionItem', PuAccordionItem],
  ['PuButton', PuButton],
  ['PuCell', PuCell],
  ['PuCheckbox', PuCheckbox],
  ['PuCheckboxGroup', PuCheckboxGroup],
  ['PuChip', PuChip],
  ['PuChipGroup', PuChipGroup],
  ['PuDescriptionItem', PuDescriptionItem],
  ['PuDescriptionList', PuDescriptionList],
  ['PuDesktopPageScaffold', PuDesktopPageScaffold],
  ['PuDrawer', PuDrawer],
  ['PuExpandableCard', PuExpandableCard],
  ['PuFooterRevealPageScaffold', PuFooterRevealPageScaffold],
  ['PuForm', PuForm],
  ['PuFormItem', PuFormItem],
  ['PuFullScreenPageScaffold', PuFullScreenPageScaffold],
  ['PuImg', PuImg],
  ['PuImgCropper', PuImgCropper],
  ['PuInfoRow', PuInfoRow],
  ['PuInput', PuInput],
  ['PuModal', PuModal],
  ['PuNoticeBar', PuNoticeBar],
  ['PuPageHeader', PuPageHeader],
  ['PuPageScaffold', PuPageScaffold],
  ['PuPageScaffoldCentered', PuPageScaffoldCentered],
  ['PuPageScaffoldFlow', PuPageScaffoldFlow],
  ['PuPicker', PuPicker],
  ['PuScrollView', PuScrollView],
  ['PuSurfaceCard', PuSurfaceCard],
  ['PuTab', PuTab],
  ['PuTabs', PuTabs],
  ['PuTag', PuTag],
  ['PuTextarea', PuTextarea],
  ['PuToggleSwitch', PuToggleSwitch],
  ['PuWheelPicker', PuWheelPicker]
]

export default components
